# Generated by Django 5.0.4 on 2024-06-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_trainer_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
